// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function Simple_(T) {
  return {};
}

function WithProps_(T) {
  return {};
}

var T = {};

var Impl = {
  Simple_: Simple_,
  WithProps_: WithProps_,
  T: T
};

var T$1;

exports.Impl = Impl;
exports.T = T$1;
/* No side effect */
