// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Random = require("bs-platform/lib/js/random.js");
var Relude_IO = require("relude/src/Relude_IO.bs.js");
var GlobalInterface$Practice = require("../../global-interface/GlobalInterface.bs.js");

var Tile = {};

function empty(param) {
  return {
          a1: [
            /* A1 */0,
            /* Empty */0
          ],
          a2: [
            /* A2 */1,
            /* Empty */0
          ],
          a3: [
            /* A3 */2,
            /* Empty */0
          ],
          b1: [
            /* B1 */3,
            /* Empty */0
          ],
          b2: [
            /* B2 */4,
            /* Empty */0
          ],
          b3: [
            /* B3 */5,
            /* Empty */0
          ],
          c1: [
            /* C1 */6,
            /* Empty */0
          ],
          c2: [
            /* C2 */7,
            /* Empty */0
          ],
          c3: [
            /* C3 */8,
            /* Empty */0
          ]
        };
}

function make(board) {
  return {
          a1: board.a1,
          a2: board.a2,
          a3: board.a3,
          b1: board.b1,
          b2: board.b2,
          b3: board.b3,
          c1: board.c1,
          c2: board.c2,
          c3: board.c3
        };
}

var include = GlobalInterface$Practice.SHOW.Default({});

var Board_show = include.show;

var Board = {
  empty: empty,
  make: make,
  show: Board_show
};

function Impl(T) {
  return {};
}

function Make(T) {
  return {};
}

var UserInterface = {
  Impl: Impl,
  Make: Make
};

function newGame(param) {
  Random.self_init(undefined);
  var randomTurn = Random.bool(undefined) === true ? /* PlayerX */0 : /* PlayerO */1;
  return {
          data: empty(undefined),
          userInterface: undefined,
          gameStatus: {
            TAG: /* InProgress */0,
            _0: randomTurn
          }
        };
}

var include$1 = GlobalInterface$Practice.SHOW.Default({});

var Game_show = include$1.show;

var Game = {
  newGame: newGame,
  show: Game_show
};

var TicTacToe = {
  Tile: undefined,
  Board: undefined,
  UserInterface: undefined,
  Game: undefined
};

var main = Relude_IO.bitap((function (prim) {
        console.log(prim);
        
      }), (function (prim) {
        console.log(prim);
        
      }), Relude_IO.suspendWithVoid(newGame));

var HtmlInterface;

exports.Tile = Tile;
exports.Board = Board;
exports.HtmlInterface = HtmlInterface;
exports.UserInterface = UserInterface;
exports.Game = Game;
exports.TicTacToe = TicTacToe;
exports.main = main;
/* include Not a pure module */
