// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function make(n) {
  return n;
}

function toString(n) {
  var str = "" + n.first;
  var v = n.second;
  var str$1 = v !== undefined ? v + str : str;
  var v$1 = n.third;
  var str$2 = v$1 !== undefined ? v$1 + str$1 : str$1;
  var v$2 = n.fourth;
  var str$3 = v$2 !== undefined ? v$2 + str$2 : str$2;
  return n.last + str$3;
}

var FullName = {
  make: make,
  toString: toString
};

exports.FullName = FullName;
/* No side effect */
