// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var ClassList = {};

var $$Event = {};

var Style = {};

exports.ClassList = ClassList;
exports.$$Event = $$Event;
exports.Style = Style;
/* No side effect */
