// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function noteFromJson(json) {
  return {
          text: Json_decode.field("text", Json_decode.string, json),
          id: Json_decode.field("id", Json_decode.string, json)
        };
}

function notesFromJson(json) {
  return Json_decode.list(noteFromJson, json);
}

function notesToJson(notes) {
  return JSON.stringify($$Array.map((function (param) {
                    var text = param.text;
                    return Js_dict.fromList({
                                hd: [
                                  "text",
                                  text
                                ],
                                tl: {
                                  hd: [
                                    "id",
                                    param.id
                                  ],
                                  tl: /* [] */0
                                }
                              });
                  }), $$Array.of_list(notes)));
}

exports.noteFromJson = noteFromJson;
exports.notesFromJson = notesFromJson;
exports.notesToJson = notesToJson;
/* No side effect */
