// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Webapi__Dom__Element = require("bs-webapi/src/Webapi/Dom/Webapi__Dom__Element.bs.js");

var $$document = document;

function onInput(param) {
  console.log("CLICKED");
  
}

function createInput(attrs) {
  var input = $$document.createElement("input");
  Belt_Array.map(attrs, (function (attr) {
          input.setAttribute(attr[0], attr[1]);
          
        }));
  input.addEventListener("input", onInput);
  return input;
}

function createLabel(attrs, innerText) {
  var label = $$document.createElement("label");
  label.innerText = innerText;
  Belt_Array.map(attrs, (function (attr) {
          label.setAttribute(attr[0], attr[1]);
          
        }));
  return label;
}

function createContainer(param) {
  var container = $$document.createElement("div");
  var el = Belt_Option.getExn(Webapi__Dom__Element.asHtmlElement(container));
  el.className = "form-example";
  el.addEventListener("click", onInput);
  return el;
}

function createForm(param) {
  var form = $$document.createElement("form");
  form.id = "mozilla";
  form.setAttribute("action", "");
  form.method = "get";
  var container1 = createContainer(undefined);
  var nameLabel1 = createLabel([[
          "label",
          "name"
        ]], "Enter your name: ");
  var nameInput1 = createInput([
        [
          "type",
          "text"
        ],
        [
          "name",
          "name"
        ],
        [
          "id",
          "name"
        ],
        [
          "required",
          "true"
        ]
      ]);
  container1.appendChild(nameLabel1);
  container1.appendChild(nameInput1);
  Belt_Option.getExn(Webapi__Dom__Element.asHtmlElement(form)).appendChild(container1);
  var container2 = createContainer(undefined);
  var nameLabel2 = createLabel([[
          "label",
          "email"
        ]], "Enter your email: ");
  var nameInput2 = createInput([
        [
          "type",
          "email"
        ],
        [
          "name",
          "email"
        ],
        [
          "id",
          "email"
        ],
        [
          "required",
          "true"
        ]
      ]);
  container2.appendChild(nameLabel2);
  container2.appendChild(nameInput2);
  Belt_Option.getExn(Webapi__Dom__Element.asHtmlElement(form)).appendChild(container2);
  var container3 = createContainer(undefined);
  var nameInput3 = createInput([
        [
          "type",
          "submit"
        ],
        [
          "value",
          "Subscribe"
        ]
      ]);
  container3.appendChild(nameInput3);
  Belt_Option.getExn(Webapi__Dom__Element.asHtmlElement(form)).appendChild(container3);
  return form;
}

function init(mainSelector) {
  var el = $$document.querySelector(mainSelector);
  var mainEl;
  if (el == null) {
    throw {
          RE_EXN_ID: "Invalid_argument",
          _1: "document.querySelector " + mainSelector,
          Error: new Error()
        };
  }
  mainEl = el;
  var moz = createForm(undefined);
  console.log("moz", moz);
  mainEl.appendChild(moz);
  
}

var D;

var $$Document;

var $$Element;

var HtmlElement;

exports.D = D;
exports.$$Document = $$Document;
exports.$$Element = $$Element;
exports.HtmlElement = HtmlElement;
exports.$$document = $$document;
exports.onInput = onInput;
exports.createInput = createInput;
exports.createLabel = createLabel;
exports.createContainer = createContainer;
exports.createForm = createForm;
exports.init = init;
/* document Not a pure module */
