// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var T = {};

var Virtual_Node_Type_Init = {};

var Child_List_Type_Init = {};

var Component_Type_Init = {};

var Abstract_Node_Type_Init = {};

var Impl = {
  T: T,
  Virtual_Node_Type_Init: Virtual_Node_Type_Init,
  Child_List_Type_Init: Child_List_Type_Init,
  Component_Type_Init: Component_Type_Init,
  Abstract_Node_Type_Init: Abstract_Node_Type_Init
};

exports.Impl = Impl;
exports.T = T;
exports.Virtual_Node_Type_Init = Virtual_Node_Type_Init;
exports.Child_List_Type_Init = Child_List_Type_Init;
exports.Component_Type_Init = Component_Type_Init;
exports.Abstract_Node_Type_Init = Abstract_Node_Type_Init;
/* No side effect */
