// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function Impl(T) {
  var Make = function (T) {
    return {};
  };
  return {
          Make: Make
        };
}

exports.Impl = Impl;
/* No side effect */
