// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function Default(T) {
  var show = function (prim) {
    return String(prim);
  };
  return {
          show: show
        };
}

function Custom(T) {
  return T;
}

var SHOW = {
  Default: Default,
  Custom: Custom
};

exports.SHOW = SHOW;
/* No side effect */
