// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function Make(M) {
  return M;
}

function map(effect) {
  var run = function () {
    effect();
    
  };
  return {
          run: run
        };
}

function bind(M) {
  var run = function () {
    return M.run();
  };
  return {
          run: run
        };
}

function join(M) {
  M.run();
  
}

function make(el, name, value) {
  switch (el.TAG | 0) {
    case /* Valid_Element */0 :
        var el$1 = el._0;
        return function (param) {
          el$1.setAttribute(name, value);
          
        };
    case /* Valid_FormElement */1 :
        var el$2 = el._0;
        return function (param) {
          el$2.setAttribute(name, value);
          
        };
    case /* Valid_InputElement */2 :
        var el$3 = el._0;
        return function (param) {
          el$3.setAttribute(name, value);
          
        };
    
  }
}

var SetAttribute = {
  make: make
};

var myEffect = map(function () {
      console.log("Side Effects!!");
      
    });

exports.Make = Make;
exports.map = map;
exports.bind = bind;
exports.join = join;
exports.SetAttribute = SetAttribute;
exports.myEffect = myEffect;
/* myEffect Not a pure module */
