// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Virtual_Node;

var Child_List;

var Dom_Effect;

var Html_Tag;

var Attribute;

var Attribute_List;

var Virtual_Event;

var Impl = {
  Virtual_Node: Virtual_Node,
  Child_List: Child_List,
  Dom_Effect: Dom_Effect,
  Html_Tag: Html_Tag,
  Attribute: Attribute,
  Attribute_List: Attribute_List,
  Virtual_Event: Virtual_Event
};

exports.Impl = Impl;
exports.Virtual_Node = Virtual_Node;
exports.Child_List = Child_List;
exports.Dom_Effect = Dom_Effect;
exports.Html_Tag = Html_Tag;
exports.Attribute = Attribute;
exports.Attribute_List = Attribute_List;
exports.Virtual_Event = Virtual_Event;
/* No side effect */
