// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function lift(x) {
  return Caml_option.some(x);
}

function flatten(x) {
  if (x === undefined) {
    return ;
  }
  var x$1 = Caml_option.valFromOption(x);
  if (x$1 !== undefined) {
    return Caml_option.some(Caml_option.valFromOption(x$1));
  }
  
}

function map(fn, x) {
  if (x !== undefined) {
    return Caml_option.some(Curry._1(fn, Caml_option.valFromOption(x)));
  }
  
}

function flatmap(fn, x) {
  return flatten(map(fn, x));
}

var OptionTools = {
  lift: lift,
  flatten: flatten,
  map: map,
  flatmap: flatmap
};

exports.OptionTools = OptionTools;
/* No side effect */
