// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var CountryCodes_afghanistan = {
  name: "Afghanistan",
  a2: "AF",
  a3: "AFG",
  num: "4",
  dial: "93"
};

var CountryCodes_albania = {
  name: "Albania",
  a2: "AL",
  a3: "ALB",
  num: "8",
  dial: "355"
};

var CountryCodes_algeria = {
  name: "Algeria",
  a2: "DZ",
  a3: "DZA",
  num: "12",
  dial: "213"
};

var CountryCodes_americanSamoa = {
  name: "American Samoa",
  a2: "AS",
  a3: "ASM",
  num: "16",
  dial: "1-684"
};

var CountryCodes_andorra = {
  name: "Andorra",
  a2: "AD",
  a3: "AND",
  num: "20",
  dial: "376"
};

var CountryCodes_angola = {
  name: "Angola",
  a2: "AO",
  a3: "AGO",
  num: "24",
  dial: "244"
};

var CountryCodes_anguilla = {
  name: "Anguilla",
  a2: "AI",
  a3: "AIA",
  num: "660",
  dial: "1-264"
};

var CountryCodes_antarctica = {
  name: "Antarctica",
  a2: "AQ",
  a3: "ATA",
  num: "10",
  dial: "672"
};

var CountryCodes_antiguaAndBarbuda = {
  name: "Antigua and Barbuda",
  a2: "AG",
  a3: "ATG",
  num: "28",
  dial: "1-268"
};

var CountryCodes_argentina = {
  name: "Argentina",
  a2: "AR",
  a3: "ARG",
  num: "32",
  dial: "54"
};

var CountryCodes_armenia = {
  name: "Armenia",
  a2: "AM",
  a3: "ARM",
  num: "51",
  dial: "374"
};

var CountryCodes_aruba = {
  name: "Aruba",
  a2: "AW",
  a3: "ABW",
  num: "533",
  dial: "297"
};

var CountryCodes_australia = {
  name: "Australia",
  a2: "AU",
  a3: "AUS",
  num: "36",
  dial: "61"
};

var CountryCodes_austria = {
  name: "Austria",
  a2: "AT",
  a3: "AUT",
  num: "40",
  dial: "43"
};

var CountryCodes_azerbaijan = {
  name: "Azerbaijan",
  a2: "AZ",
  a3: "AZE",
  num: "31",
  dial: "994"
};

var CountryCodes_bahamas = {
  name: "Bahamas",
  a2: "BS",
  a3: "BHS",
  num: "44",
  dial: "1-242"
};

var CountryCodes_bahrain = {
  name: "Bahrain",
  a2: "BH",
  a3: "BHR",
  num: "48",
  dial: "973"
};

var CountryCodes_bangladesh = {
  name: "Bangladesh",
  a2: "BD",
  a3: "BGD",
  num: "50",
  dial: "880"
};

var CountryCodes_barbados = {
  name: "Barbados",
  a2: "BB",
  a3: "BRB",
  num: "52",
  dial: "1-246"
};

var CountryCodes_belarus = {
  name: "Belarus",
  a2: "BY",
  a3: "BLR",
  num: "112",
  dial: "375"
};

var CountryCodes_belgium = {
  name: "Belgium",
  a2: "BE",
  a3: "BEL",
  num: "56",
  dial: "32"
};

var CountryCodes_belize = {
  name: "Belize",
  a2: "BZ",
  a3: "BLZ",
  num: "84",
  dial: "501"
};

var CountryCodes_benin = {
  name: "Benin",
  a2: "BJ",
  a3: "BEN",
  num: "204",
  dial: "229"
};

var CountryCodes_bermuda = {
  name: "Bermuda",
  a2: "BM",
  a3: "BMU",
  num: "60",
  dial: "1-441"
};

var CountryCodes_bhutan = {
  name: "Bhutan",
  a2: "BT",
  a3: "BTN",
  num: "64",
  dial: "975"
};

var CountryCodes_bolivia = {
  name: "Bolivia",
  a2: "BO",
  a3: "BOL",
  num: "68",
  dial: "591"
};

var CountryCodes_bonaire = {
  name: "Bonaire",
  a2: "BQ",
  a3: "BES",
  num: "535",
  dial: "599"
};

var CountryCodes_bosniaAndHerzegovina = {
  name: "Bosnia and Herzegovina",
  a2: "BA",
  a3: "BIH",
  num: "70",
  dial: "387"
};

var CountryCodes_botswana = {
  name: "Botswana",
  a2: "BW",
  a3: "BWA",
  num: "72",
  dial: "267"
};

var CountryCodes_bouvetIsland = {
  name: "Bouvet Island",
  a2: "BV",
  a3: "BVT",
  num: "74",
  dial: "47"
};

var CountryCodes_brazil = {
  name: "Brazil",
  a2: "BR",
  a3: "BRA",
  num: "76",
  dial: "55"
};

var CountryCodes_britishIndianOceanTerritory = {
  name: "British Indian Ocean Territory",
  a2: "IO",
  a3: "IOT",
  num: "86",
  dial: "246"
};

var CountryCodes_bruneiDarussalam = {
  name: "Brunei Darussalam",
  a2: "BN",
  a3: "BRN",
  num: "96",
  dial: "673"
};

var CountryCodes_bulgaria = {
  name: "Bulgaria",
  a2: "BG",
  a3: "BGR",
  num: "100",
  dial: "359"
};

var CountryCodes_burkinaFaso = {
  name: "Burkina Faso",
  a2: "BF",
  a3: "BFA",
  num: "854",
  dial: "226"
};

var CountryCodes_burundi = {
  name: "Burundi",
  a2: "BI",
  a3: "BDI",
  num: "108",
  dial: "257"
};

var CountryCodes_cambodia = {
  name: "Cambodia",
  a2: "KH",
  a3: "KHM",
  num: "116",
  dial: "855"
};

var CountryCodes_cameroon = {
  name: "Cameroon",
  a2: "CM",
  a3: "CMR",
  num: "120",
  dial: "237"
};

var CountryCodes_canada = {
  name: "Canada",
  a2: "CA",
  a3: "CAN",
  num: "124",
  dial: "1"
};

var CountryCodes_capeVerde = {
  name: "Cape Verde",
  a2: "CV",
  a3: "CPV",
  num: "132",
  dial: "238"
};

var CountryCodes_caymanIslands = {
  name: "Cayman Islands",
  a2: "KY",
  a3: "CYM",
  num: "136",
  dial: "1-345"
};

var CountryCodes_centralAfricanRepublic = {
  name: "Central African Republic",
  a2: "CF",
  a3: "CAF",
  num: "140",
  dial: "236"
};

var CountryCodes_chad = {
  name: "Chad",
  a2: "TD",
  a3: "TCD",
  num: "148",
  dial: "235"
};

var CountryCodes_chile = {
  name: "Chile",
  a2: "CL",
  a3: "CHL",
  num: "152",
  dial: "56"
};

var CountryCodes_china = {
  name: "China",
  a2: "CN",
  a3: "CHN",
  num: "156",
  dial: "86"
};

var CountryCodes_christmasIsland = {
  name: "Christmas Island",
  a2: "CX",
  a3: "CXR",
  num: "162",
  dial: "61"
};

var CountryCodes_cocosKeelingIslands = {
  name: "Cocos (Keeling) Islands",
  a2: "CC",
  a3: "CCK",
  num: "166",
  dial: "61"
};

var CountryCodes_colombia = {
  name: "Colombia",
  a2: "CO",
  a3: "COL",
  num: "170",
  dial: "57"
};

var CountryCodes_comoros = {
  name: "Comoros",
  a2: "KM",
  a3: "COM",
  num: "174",
  dial: "269"
};

var CountryCodes_congo = {
  name: "Congo",
  a2: "CG",
  a3: "COG",
  num: "178",
  dial: "242"
};

var CountryCodes_democraticRepublicOfTheCongo = {
  name: "Democratic Republic of the Congo",
  a2: "CD",
  a3: "COD",
  num: "180",
  dial: "243"
};

var CountryCodes_cookIslands = {
  name: "Cook Islands",
  a2: "CK",
  a3: "COK",
  num: "184",
  dial: "682"
};

var CountryCodes_costaRica = {
  name: "Costa Rica",
  a2: "CR",
  a3: "CRI",
  num: "188",
  dial: "506"
};

var CountryCodes_croatia = {
  name: "Croatia",
  a2: "HR",
  a3: "HRV",
  num: "191",
  dial: "385"
};

var CountryCodes_cuba = {
  name: "Cuba",
  a2: "CU",
  a3: "CUB",
  num: "192",
  dial: "53"
};

var CountryCodes_curacao = {
  name: "Curacao",
  a2: "CW",
  a3: "CUW",
  num: "531",
  dial: "599"
};

var CountryCodes_cyprus = {
  name: "Cyprus",
  a2: "CY",
  a3: "CYP",
  num: "196",
  dial: "357"
};

var CountryCodes_czechRepublic = {
  name: "Czech Republic",
  a2: "CZ",
  a3: "CZE",
  num: "203",
  dial: "420"
};

var CountryCodes_coteDIvoire = {
  name: "Cote d'Ivoire",
  a2: "CI",
  a3: "CIV",
  num: "384",
  dial: "225"
};

var CountryCodes_denmark = {
  name: "Denmark",
  a2: "DK",
  a3: "DNK",
  num: "208",
  dial: "45"
};

var CountryCodes_djibouti = {
  name: "Djibouti",
  a2: "DJ",
  a3: "DJI",
  num: "262",
  dial: "253"
};

var CountryCodes_dominica = {
  name: "Dominica",
  a2: "DM",
  a3: "DMA",
  num: "212",
  dial: "1-767"
};

var CountryCodes_dominicanRepublic = {
  name: "Dominican Republic",
  a2: "DO",
  a3: "DOM",
  num: "214",
  dial: "1-809,1-829,1-849"
};

var CountryCodes_ecuador = {
  name: "Ecuador",
  a2: "EC",
  a3: "ECU",
  num: "218",
  dial: "593"
};

var CountryCodes_egypt = {
  name: "Egypt",
  a2: "EG",
  a3: "EGY",
  num: "818",
  dial: "20"
};

var CountryCodes_elSalvador = {
  name: "El Salvador",
  a2: "SV",
  a3: "SLV",
  num: "222",
  dial: "503"
};

var CountryCodes_equatorialGuinea = {
  name: "Equatorial Guinea",
  a2: "GQ",
  a3: "GNQ",
  num: "226",
  dial: "240"
};

var CountryCodes_eritrea = {
  name: "Eritrea",
  a2: "ER",
  a3: "ERI",
  num: "232",
  dial: "291"
};

var CountryCodes_estonia = {
  name: "Estonia",
  a2: "EE",
  a3: "EST",
  num: "233",
  dial: "372"
};

var CountryCodes_ethiopia = {
  name: "Ethiopia",
  a2: "ET",
  a3: "ETH",
  num: "231",
  dial: "251"
};

var CountryCodes_falklandIslandsMalvinas = {
  name: "Falkland Islands (Malvinas)",
  a2: "FK",
  a3: "FLK",
  num: "238",
  dial: "500"
};

var CountryCodes_faroeIslands = {
  name: "Faroe Islands",
  a2: "FO",
  a3: "FRO",
  num: "234",
  dial: "298"
};

var CountryCodes_fiji = {
  name: "Fiji",
  a2: "FJ",
  a3: "FJI",
  num: "242",
  dial: "679"
};

var CountryCodes_finland = {
  name: "Finland",
  a2: "FI",
  a3: "FIN",
  num: "246",
  dial: "358"
};

var CountryCodes_france = {
  name: "France",
  a2: "FR",
  a3: "FRA",
  num: "250",
  dial: "33"
};

var CountryCodes_frenchGuiana = {
  name: "French Guiana",
  a2: "GF",
  a3: "GUF",
  num: "254",
  dial: "594"
};

var CountryCodes_frenchPolynesia = {
  name: "French Polynesia",
  a2: "PF",
  a3: "PYF",
  num: "258",
  dial: "689"
};

var CountryCodes_frenchSouthernTerritories = {
  name: "French Southern Territories",
  a2: "TF",
  a3: "ATF",
  num: "260",
  dial: "262"
};

var CountryCodes_gabon = {
  name: "Gabon",
  a2: "GA",
  a3: "GAB",
  num: "266",
  dial: "241"
};

var CountryCodes_gambia = {
  name: "Gambia",
  a2: "GM",
  a3: "GMB",
  num: "270",
  dial: "220"
};

var CountryCodes_georgia = {
  name: "Georgia",
  a2: "GE",
  a3: "GEO",
  num: "268",
  dial: "995"
};

var CountryCodes_germany = {
  name: "Germany",
  a2: "DE",
  a3: "DEU",
  num: "276",
  dial: "49"
};

var CountryCodes_ghana = {
  name: "Ghana",
  a2: "GH",
  a3: "GHA",
  num: "288",
  dial: "233"
};

var CountryCodes_gibraltar = {
  name: "Gibraltar",
  a2: "GI",
  a3: "GIB",
  num: "292",
  dial: "350"
};

var CountryCodes_greece = {
  name: "Greece",
  a2: "GR",
  a3: "GRC",
  num: "300",
  dial: "30"
};

var CountryCodes_greenland = {
  name: "Greenland",
  a2: "GL",
  a3: "GRL",
  num: "304",
  dial: "299"
};

var CountryCodes_grenada = {
  name: "Grenada",
  a2: "GD",
  a3: "GRD",
  num: "308",
  dial: "1-473"
};

var CountryCodes_guadeloupe = {
  name: "Guadeloupe",
  a2: "GP",
  a3: "GLP",
  num: "312",
  dial: "590"
};

var CountryCodes_guam = {
  name: "Guam",
  a2: "GU",
  a3: "GUM",
  num: "316",
  dial: "1-671"
};

var CountryCodes_guatemala = {
  name: "Guatemala",
  a2: "GT",
  a3: "GTM",
  num: "320",
  dial: "502"
};

var CountryCodes_guernsey = {
  name: "Guernsey",
  a2: "GG",
  a3: "GGY",
  num: "831",
  dial: "44"
};

var CountryCodes_guinea = {
  name: "Guinea",
  a2: "GN",
  a3: "GIN",
  num: "324",
  dial: "224"
};

var CountryCodes_guineaBissau = {
  name: "Guinea-Bissau",
  a2: "GW",
  a3: "GNB",
  num: "624",
  dial: "245"
};

var CountryCodes_guyana = {
  name: "Guyana",
  a2: "GY",
  a3: "GUY",
  num: "328",
  dial: "592"
};

var CountryCodes_haiti = {
  name: "Haiti",
  a2: "HT",
  a3: "HTI",
  num: "332",
  dial: "509"
};

var CountryCodes_heardIslandAndMcDonaldIslands = {
  name: "Heard Island and McDonald Islands",
  a2: "HM",
  a3: "HMD",
  num: "334",
  dial: "672"
};

var CountryCodes_honduras = {
  name: "Honduras",
  a2: "HN",
  a3: "HND",
  num: "340",
  dial: "504"
};

var CountryCodes_hongKong = {
  name: "Hong Kong",
  a2: "HK",
  a3: "HKG",
  num: "344",
  dial: "852"
};

var CountryCodes_hungary = {
  name: "Hungary",
  a2: "HU",
  a3: "HUN",
  num: "348",
  dial: "36"
};

var CountryCodes_iceland = {
  name: "Iceland",
  a2: "IS",
  a3: "ISL",
  num: "352",
  dial: "354"
};

var CountryCodes_india = {
  name: "India",
  a2: "IN",
  a3: "IND",
  num: "356",
  dial: "91"
};

var CountryCodes_indonesia = {
  name: "Indonesia",
  a2: "ID",
  a3: "IDN",
  num: "360",
  dial: "62"
};

var CountryCodes_iran = {
  name: "Iran, Islamic Republic of",
  a2: "IR",
  a3: "IRN",
  num: "364",
  dial: "98"
};

var CountryCodes_iraq = {
  name: "Iraq",
  a2: "IQ",
  a3: "IRQ",
  num: "368",
  dial: "964"
};

var CountryCodes_ireland = {
  name: "Ireland",
  a2: "IE",
  a3: "IRL",
  num: "372",
  dial: "353"
};

var CountryCodes_isleofMan = {
  name: "Isle of Man",
  a2: "IM",
  a3: "IMN",
  num: "833",
  dial: "44"
};

var CountryCodes_israel = {
  name: "Israel",
  a2: "IL",
  a3: "ISR",
  num: "376",
  dial: "972"
};

var CountryCodes_italy = {
  name: "Italy",
  a2: "IT",
  a3: "ITA",
  num: "380",
  dial: "39"
};

var CountryCodes_jamaica = {
  name: "Jamaica",
  a2: "JM",
  a3: "JAM",
  num: "388",
  dial: "1-876"
};

var CountryCodes_japan = {
  name: "Japan",
  a2: "JP",
  a3: "JPN",
  num: "392",
  dial: "81"
};

var CountryCodes_jersey = {
  name: "Jersey",
  a2: "JE",
  a3: "JEY",
  num: "832",
  dial: "44"
};

var CountryCodes_jordan = {
  name: "Jordan",
  a2: "JO",
  a3: "JOR",
  num: "400",
  dial: "962"
};

var CountryCodes_kazakhstan = {
  name: "Kazakhstan",
  a2: "KZ",
  a3: "KAZ",
  num: "398",
  dial: "7"
};

var CountryCodes_kenya = {
  name: "Kenya",
  a2: "KE",
  a3: "KEN",
  num: "404",
  dial: "254"
};

var CountryCodes_kiribati = {
  name: "Kiribati",
  a2: "KI",
  a3: "KIR",
  num: "296",
  dial: "686"
};

var CountryCodes_northKorea = {
  name: "Korea, Democratic People's Republic of",
  a2: "KP",
  a3: "PRK",
  num: "408",
  dial: "850"
};

var CountryCodes_southKorea = {
  name: "Korea, Republic of",
  a2: "KR",
  a3: "KOR",
  num: "410",
  dial: "82"
};

var CountryCodes_kuwait = {
  name: "Kuwait",
  a2: "KW",
  a3: "KWT",
  num: "414",
  dial: "965"
};

var CountryCodes_kyrgyzstan = {
  name: "Kyrgyzstan",
  a2: "KG",
  a3: "KGZ",
  num: "417",
  dial: "996"
};

var CountryCodes_lao = {
  name: "Lao People's Democratic Republic",
  a2: "LA",
  a3: "LAO",
  num: "418",
  dial: "856"
};

var CountryCodes_latvia = {
  name: "Latvia",
  a2: "LV",
  a3: "LVA",
  num: "428",
  dial: "371"
};

var CountryCodes_lebanon = {
  name: "Lebanon",
  a2: "LB",
  a3: "LBN",
  num: "422",
  dial: "961"
};

var CountryCodes_lesotho = {
  name: "Lesotho",
  a2: "LS",
  a3: "LSO",
  num: "426",
  dial: "266"
};

var CountryCodes_liberia = {
  name: "Liberia",
  a2: "LR",
  a3: "LBR",
  num: "430",
  dial: "231"
};

var CountryCodes_libya = {
  name: "Libya",
  a2: "LY",
  a3: "LBY",
  num: "434",
  dial: "218"
};

var CountryCodes_liechtenstein = {
  name: "Liechtenstein",
  a2: "LI",
  a3: "LIE",
  num: "438",
  dial: "423"
};

var CountryCodes_lithuania = {
  name: "Lithuania",
  a2: "LT",
  a3: "LTU",
  num: "440",
  dial: "370"
};

var CountryCodes_luxembourg = {
  name: "Luxembourg",
  a2: "LU",
  a3: "LUX",
  num: "442",
  dial: "352"
};

var CountryCodes_macao = {
  name: "Macao",
  a2: "MO",
  a3: "MAC",
  num: "446",
  dial: "853"
};

var CountryCodes_macedonia = {
  name: "Macedonia, the Former Yugoslav Republic of",
  a2: "MK",
  a3: "MKD",
  num: "807",
  dial: "389"
};

var CountryCodes_madagascar = {
  name: "Madagascar",
  a2: "MG",
  a3: "MDG",
  num: "450",
  dial: "261"
};

var CountryCodes_malawi = {
  name: "Malawi",
  a2: "MW",
  a3: "MWI",
  num: "454",
  dial: "265"
};

var CountryCodes_malaysia = {
  name: "Malaysia",
  a2: "MY",
  a3: "MYS",
  num: "458",
  dial: "60"
};

var CountryCodes_maldives = {
  name: "Maldives",
  a2: "MV",
  a3: "MDV",
  num: "462",
  dial: "960"
};

var CountryCodes_mali = {
  name: "Mali",
  a2: "ML",
  a3: "MLI",
  num: "466",
  dial: "223"
};

var CountryCodes_malta = {
  name: "Malta",
  a2: "MT",
  a3: "MLT",
  num: "470",
  dial: "356"
};

var CountryCodes_marshallIslands = {
  name: "Marshall Islands",
  a2: "MH",
  a3: "MHL",
  num: "584",
  dial: "692"
};

var CountryCodes_martinique = {
  name: "Martinique",
  a2: "MQ",
  a3: "MTQ",
  num: "474",
  dial: "596"
};

var CountryCodes_mauritania = {
  name: "Mauritania",
  a2: "MR",
  a3: "MRT",
  num: "478",
  dial: "222"
};

var CountryCodes_mauritius = {
  name: "Mauritius",
  a2: "MU",
  a3: "MUS",
  num: "480",
  dial: "230"
};

var CountryCodes_mayotte = {
  name: "Mayotte",
  a2: "YT",
  a3: "MYT",
  num: "175",
  dial: "262"
};

var CountryCodes_mexico = {
  name: "Mexico",
  a2: "MX",
  a3: "MEX",
  num: "484",
  dial: "52"
};

var CountryCodes_micronesia = {
  name: "Micronesia, Federated States of",
  a2: "FM",
  a3: "FSM",
  num: "583",
  dial: "691"
};

var CountryCodes_moldova = {
  name: "Moldova, Republic of",
  a2: "MD",
  a3: "MDA",
  num: "498",
  dial: "373"
};

var CountryCodes_monaco = {
  name: "Monaco",
  a2: "MC",
  a3: "MCO",
  num: "492",
  dial: "377"
};

var CountryCodes_mongolia = {
  name: "Mongolia",
  a2: "MN",
  a3: "MNG",
  num: "496",
  dial: "976"
};

var CountryCodes_montenegro = {
  name: "Montenegro",
  a2: "ME",
  a3: "MNE",
  num: "499",
  dial: "382"
};

var CountryCodes_montserrat = {
  name: "Montserrat",
  a2: "MS",
  a3: "MSR",
  num: "500",
  dial: "1-664"
};

var CountryCodes_morocco = {
  name: "Morocco",
  a2: "MA",
  a3: "MAR",
  num: "504",
  dial: "212"
};

var CountryCodes_mozambique = {
  name: "Mozambique",
  a2: "MZ",
  a3: "MOZ",
  num: "508",
  dial: "258"
};

var CountryCodes_myanmar = {
  name: "Myanmar",
  a2: "MM",
  a3: "MMR",
  num: "104",
  dial: "95"
};

var CountryCodes_namibia = {
  name: "Namibia",
  a2: "NA",
  a3: "NAM",
  num: "516",
  dial: "264"
};

var CountryCodes_nauru = {
  name: "Nauru",
  a2: "NR",
  a3: "NRU",
  num: "520",
  dial: "674"
};

var CountryCodes_nepal = {
  name: "Nepal",
  a2: "NP",
  a3: "NPL",
  num: "524",
  dial: "977"
};

var CountryCodes_netherlands = {
  name: "Netherlands",
  a2: "NL",
  a3: "NLD",
  num: "528",
  dial: "31"
};

var CountryCodes_newCaledonia = {
  name: "New Caledonia",
  a2: "NC",
  a3: "NCL",
  num: "540",
  dial: "687"
};

var CountryCodes_newZealand = {
  name: "New Zealand",
  a2: "NZ",
  a3: "NZL",
  num: "554",
  dial: "64"
};

var CountryCodes_nicaragua = {
  name: "Nicaragua",
  a2: "NI",
  a3: "NIC",
  num: "558",
  dial: "505"
};

var CountryCodes_niger = {
  name: "Niger",
  a2: "NE",
  a3: "NER",
  num: "562",
  dial: "227"
};

var CountryCodes_nigeria = {
  name: "Nigeria",
  a2: "NG",
  a3: "NGA",
  num: "566",
  dial: "234"
};

var CountryCodes_niue = {
  name: "Niue",
  a2: "NU",
  a3: "NIU",
  num: "570",
  dial: "683"
};

var CountryCodes_norfolkIsland = {
  name: "Norfolk Island",
  a2: "NF",
  a3: "NFK",
  num: "574",
  dial: "672"
};

var CountryCodes_northernMarianaIslands = {
  name: "Northern Mariana Islands",
  a2: "MP",
  a3: "MNP",
  num: "580",
  dial: "1-670"
};

var CountryCodes_norway = {
  name: "Norway",
  a2: "NO",
  a3: "NOR",
  num: "578",
  dial: "47"
};

var CountryCodes_oman = {
  name: "Oman",
  a2: "OM",
  a3: "OMN",
  num: "512",
  dial: "968"
};

var CountryCodes_pakistan = {
  name: "Pakistan",
  a2: "PK",
  a3: "PAK",
  num: "586",
  dial: "92"
};

var CountryCodes_palau = {
  name: "Palau",
  a2: "PW",
  a3: "PLW",
  num: "585",
  dial: "680"
};

var CountryCodes_palestine = {
  name: "Palestine, State of",
  a2: "PS",
  a3: "PSE",
  num: "275",
  dial: "970"
};

var CountryCodes_panama = {
  name: "Panama",
  a2: "PA",
  a3: "PAN",
  num: "591",
  dial: "507"
};

var CountryCodes_papuaNewGuinea = {
  name: "Papua New Guinea",
  a2: "PG",
  a3: "PNG",
  num: "598",
  dial: "675"
};

var CountryCodes_paraguay = {
  name: "Paraguay",
  a2: "PY",
  a3: "PRY",
  num: "600",
  dial: "595"
};

var CountryCodes_peru = {
  name: "Peru",
  a2: "PE",
  a3: "PER",
  num: "604",
  dial: "51"
};

var CountryCodes_philippines = {
  name: "Philippines",
  a2: "PH",
  a3: "PHL",
  num: "608",
  dial: "63"
};

var CountryCodes_pitcairn = {
  name: "Pitcairn",
  a2: "PN",
  a3: "PCN",
  num: "612",
  dial: "870"
};

var CountryCodes_poland = {
  name: "Poland",
  a2: "PL",
  a3: "POL",
  num: "616",
  dial: "48"
};

var CountryCodes_portugal = {
  name: "Portugal",
  a2: "PT",
  a3: "PRT",
  num: "620",
  dial: "351"
};

var CountryCodes_puertoRico = {
  name: "Puerto Rico",
  a2: "PR",
  a3: "PRI",
  num: "630",
  dial: "1"
};

var CountryCodes_qatar = {
  name: "Qatar",
  a2: "QA",
  a3: "QAT",
  num: "634",
  dial: "974"
};

var CountryCodes_romania = {
  name: "Romania",
  a2: "RO",
  a3: "ROU",
  num: "642",
  dial: "40"
};

var CountryCodes_russianFederation = {
  name: "Russian Federation",
  a2: "RU",
  a3: "RUS",
  num: "643",
  dial: "7"
};

var CountryCodes_rwanda = {
  name: "Rwanda",
  a2: "RW",
  a3: "RWA",
  num: "646",
  dial: "250"
};

var CountryCodes_reunion = {
  name: "Reunion",
  a2: "RE",
  a3: "REU",
  num: "638",
  dial: "262"
};

var CountryCodes_saintBarthelemy = {
  name: "Saint Barthelemy",
  a2: "BL",
  a3: "BLM",
  num: "652",
  dial: "590"
};

var CountryCodes_saintHelena = {
  name: "Saint Helena",
  a2: "SH",
  a3: "SHN",
  num: "654",
  dial: "290"
};

var CountryCodes_saintKittsAndNevis = {
  name: "Saint Kitts and Nevis",
  a2: "KN",
  a3: "KNA",
  num: "659",
  dial: "1-869"
};

var CountryCodes_saintLucia = {
  name: "Saint Lucia",
  a2: "LC",
  a3: "LCA",
  num: "662",
  dial: "1-758"
};

var CountryCodes_saintMartinFrenchPart = {
  name: "Saint Martin (French part)",
  a2: "MF",
  a3: "MAF",
  num: "663",
  dial: "590"
};

var CountryCodes_saintPierreAndMiquelon = {
  name: "Saint Pierre and Miquelon",
  a2: "PM",
  a3: "SPM",
  num: "666",
  dial: "508"
};

var CountryCodes_saintVincentAndtheGrenadines = {
  name: "Saint Vincent and the Grenadines",
  a2: "VC",
  a3: "VCT",
  num: "670",
  dial: "1-784"
};

var CountryCodes_samoa = {
  name: "Samoa",
  a2: "WS",
  a3: "WSM",
  num: "882",
  dial: "685"
};

var CountryCodes_sanMarino = {
  name: "San Marino",
  a2: "SM",
  a3: "SMR",
  num: "674",
  dial: "378"
};

var CountryCodes_saoTomeAndPrincipe = {
  name: "Sao Tome and Principe",
  a2: "ST",
  a3: "STP",
  num: "678",
  dial: "239"
};

var CountryCodes_saudiArabia = {
  name: "Saudi Arabia",
  a2: "SA",
  a3: "SAU",
  num: "682",
  dial: "966"
};

var CountryCodes_senegal = {
  name: "Senegal",
  a2: "SN",
  a3: "SEN",
  num: "686",
  dial: "221"
};

var CountryCodes_serbia = {
  name: "Serbia",
  a2: "RS",
  a3: "SRB",
  num: "688",
  dial: "381"
};

var CountryCodes_seychelles = {
  name: "Seychelles",
  a2: "SC",
  a3: "SYC",
  num: "690",
  dial: "248"
};

var CountryCodes_sierraLeone = {
  name: "Sierra Leone",
  a2: "SL",
  a3: "SLE",
  num: "694",
  dial: "232"
};

var CountryCodes_singapore = {
  name: "Singapore",
  a2: "SG",
  a3: "SGP",
  num: "702",
  dial: "65"
};

var CountryCodes_sintMaartenDutchPart = {
  name: "Sint Maarten (Dutch part)",
  a2: "SX",
  a3: "SXM",
  num: "534",
  dial: "1-721"
};

var CountryCodes_slovakia = {
  name: "Slovakia",
  a2: "SK",
  a3: "SVK",
  num: "703",
  dial: "421"
};

var CountryCodes_slovenia = {
  name: "Slovenia",
  a2: "SI",
  a3: "SVN",
  num: "705",
  dial: "386"
};

var CountryCodes_solomonIslands = {
  name: "Solomon Islands",
  a2: "SB",
  a3: "SLB",
  num: "90",
  dial: "677"
};

var CountryCodes_somalia = {
  name: "Somalia",
  a2: "SO",
  a3: "SOM",
  num: "706",
  dial: "252"
};

var CountryCodes_southAfrica = {
  name: "South Africa",
  a2: "ZA",
  a3: "ZAF",
  num: "710",
  dial: "27"
};

var CountryCodes_southGeorgiaAndtheSouthSandwichIslands = {
  name: "South Georgia and the South Sandwich Islands",
  a2: "GS",
  a3: "SGS",
  num: "239",
  dial: "500"
};

var CountryCodes_southSudan = {
  name: "South Sudan",
  a2: "SS",
  a3: "SSD",
  num: "728",
  dial: "211"
};

var CountryCodes_spain = {
  name: "Spain",
  a2: "ES",
  a3: "ESP",
  num: "724",
  dial: "34"
};

var CountryCodes_sriLanka = {
  name: "Sri Lanka",
  a2: "LK",
  a3: "LKA",
  num: "144",
  dial: "94"
};

var CountryCodes_sudan = {
  name: "Sudan",
  a2: "SD",
  a3: "SDN",
  num: "729",
  dial: "249"
};

var CountryCodes_suriname = {
  name: "Suriname",
  a2: "SR",
  a3: "SUR",
  num: "740",
  dial: "597"
};

var CountryCodes_svalbardAndJanMayen = {
  name: "Svalbard and Jan Mayen",
  a2: "SJ",
  a3: "SJM",
  num: "744",
  dial: "47"
};

var CountryCodes_swaziland = {
  name: "Swaziland",
  a2: "SZ",
  a3: "SWZ",
  num: "748",
  dial: "268"
};

var CountryCodes_sweden = {
  name: "Sweden",
  a2: "SE",
  a3: "SWE",
  num: "752",
  dial: "46"
};

var CountryCodes_switzerland = {
  name: "Switzerland",
  a2: "CH",
  a3: "CHE",
  num: "756",
  dial: "41"
};

var CountryCodes_syrianArabRepublic = {
  name: "Syrian Arab Republic",
  a2: "SY",
  a3: "SYR",
  num: "760",
  dial: "963"
};

var CountryCodes_taiwan = {
  name: "Taiwan",
  a2: "TW",
  a3: "TWN",
  num: "158",
  dial: "886"
};

var CountryCodes_tajikistan = {
  name: "Tajikistan",
  a2: "TJ",
  a3: "TJK",
  num: "762",
  dial: "992"
};

var CountryCodes_unitedRepublicOfTanzania = {
  name: "United Republic of Tanzania",
  a2: "TZ",
  a3: "TZA",
  num: "834",
  dial: "255"
};

var CountryCodes_thailand = {
  name: "Thailand",
  a2: "TH",
  a3: "THA",
  num: "764",
  dial: "66"
};

var CountryCodes_timorLeste = {
  name: "Timor-Leste",
  a2: "TL",
  a3: "TLS",
  num: "626",
  dial: "670"
};

var CountryCodes_togo = {
  name: "Togo",
  a2: "TG",
  a3: "TGO",
  num: "768",
  dial: "228"
};

var CountryCodes_tokelau = {
  name: "Tokelau",
  a2: "TK",
  a3: "TKL",
  num: "772",
  dial: "690"
};

var CountryCodes_tonga = {
  name: "Tonga",
  a2: "TO",
  a3: "TON",
  num: "776",
  dial: "676"
};

var CountryCodes_trinidadAndTobago = {
  name: "Trinidad and Tobago",
  a2: "TT",
  a3: "TTO",
  num: "780",
  dial: "1-868"
};

var CountryCodes_tunisia = {
  name: "Tunisia",
  a2: "TN",
  a3: "TUN",
  num: "788",
  dial: "216"
};

var CountryCodes_turkey = {
  name: "Turkey",
  a2: "TR",
  a3: "TUR",
  num: "792",
  dial: "90"
};

var CountryCodes_turkmenistan = {
  name: "Turkmenistan",
  a2: "TM",
  a3: "TKM",
  num: "795",
  dial: "993"
};

var CountryCodes_turksandCaicosIslands = {
  name: "Turks and Caicos Islands",
  a2: "TC",
  a3: "TCA",
  num: "796",
  dial: "1-649"
};

var CountryCodes_tuvalu = {
  name: "Tuvalu",
  a2: "TV",
  a3: "TUV",
  num: "798",
  dial: "688"
};

var CountryCodes_uganda = {
  name: "Uganda",
  a2: "UG",
  a3: "UGA",
  num: "800",
  dial: "256"
};

var CountryCodes_ukraine = {
  name: "Ukraine",
  a2: "UA",
  a3: "UKR",
  num: "804",
  dial: "380"
};

var CountryCodes_unitedArabEmirates = {
  name: "United Arab Emirates",
  a2: "AE",
  a3: "ARE",
  num: "784",
  dial: "971"
};

var CountryCodes_unitedKingdom = {
  name: "United Kingdom",
  a2: "GB",
  a3: "GBR",
  num: "826",
  dial: "44"
};

var CountryCodes_unitedStates = {
  name: "United States",
  a2: "US",
  a3: "USA",
  num: "840",
  dial: "1"
};

var CountryCodes_unitedStatesMinorOutlyingIslands = {
  name: "United States Minor Outlying Islands",
  a2: "UM",
  a3: "UMI",
  num: "581",
  dial: "1"
};

var CountryCodes_uruguay = {
  name: "Uruguay",
  a2: "UY",
  a3: "URY",
  num: "858",
  dial: "598"
};

var CountryCodes_uzbekistan = {
  name: "Uzbekistan",
  a2: "UZ",
  a3: "UZB",
  num: "860",
  dial: "998"
};

var CountryCodes_vanuatu = {
  name: "Vanuatu",
  a2: "VU",
  a3: "VUT",
  num: "548",
  dial: "678"
};

var CountryCodes_vaticanCityState = {
  name: "Holy See (Vatican City State)",
  a2: "VA",
  a3: "VAT",
  num: "336",
  dial: "379"
};

var CountryCodes_venezuela = {
  name: "Venezuela",
  a2: "VE",
  a3: "VEN",
  num: "862",
  dial: "58"
};

var CountryCodes_vietNam = {
  name: "Viet Nam",
  a2: "VN",
  a3: "VNM",
  num: "704",
  dial: "84"
};

var CountryCodes_britishVirginIslands = {
  name: "British Virgin Islands",
  a2: "VG",
  a3: "VGB",
  num: "92",
  dial: "1-284"
};

var CountryCodes_usVirginIslands = {
  name: "US Virgin Islands",
  a2: "VI",
  a3: "VIR",
  num: "850",
  dial: "1-340"
};

var CountryCodes_wallisAndFutuna = {
  name: "Wallis and Futuna",
  a2: "WF",
  a3: "WLF",
  num: "876",
  dial: "681"
};

var CountryCodes_westernSahara = {
  name: "Western Sahara",
  a2: "EH",
  a3: "ESH",
  num: "732",
  dial: "212"
};

var CountryCodes_yemen = {
  name: "Yemen",
  a2: "YE",
  a3: "YEM",
  num: "887",
  dial: "967"
};

var CountryCodes_zambia = {
  name: "Zambia",
  a2: "ZM",
  a3: "ZMB",
  num: "894",
  dial: "260"
};

var CountryCodes_zimbabwe = {
  name: "Zimbabwe",
  a2: "ZW",
  a3: "ZWE",
  num: "716",
  dial: "263"
};

var CountryCodes = {
  afghanistan: CountryCodes_afghanistan,
  albania: CountryCodes_albania,
  algeria: CountryCodes_algeria,
  americanSamoa: CountryCodes_americanSamoa,
  andorra: CountryCodes_andorra,
  angola: CountryCodes_angola,
  anguilla: CountryCodes_anguilla,
  antarctica: CountryCodes_antarctica,
  antiguaAndBarbuda: CountryCodes_antiguaAndBarbuda,
  argentina: CountryCodes_argentina,
  armenia: CountryCodes_armenia,
  aruba: CountryCodes_aruba,
  australia: CountryCodes_australia,
  austria: CountryCodes_austria,
  azerbaijan: CountryCodes_azerbaijan,
  bahamas: CountryCodes_bahamas,
  bahrain: CountryCodes_bahrain,
  bangladesh: CountryCodes_bangladesh,
  barbados: CountryCodes_barbados,
  belarus: CountryCodes_belarus,
  belgium: CountryCodes_belgium,
  belize: CountryCodes_belize,
  benin: CountryCodes_benin,
  bermuda: CountryCodes_bermuda,
  bhutan: CountryCodes_bhutan,
  bolivia: CountryCodes_bolivia,
  bonaire: CountryCodes_bonaire,
  bosniaAndHerzegovina: CountryCodes_bosniaAndHerzegovina,
  botswana: CountryCodes_botswana,
  bouvetIsland: CountryCodes_bouvetIsland,
  brazil: CountryCodes_brazil,
  britishIndianOceanTerritory: CountryCodes_britishIndianOceanTerritory,
  bruneiDarussalam: CountryCodes_bruneiDarussalam,
  bulgaria: CountryCodes_bulgaria,
  burkinaFaso: CountryCodes_burkinaFaso,
  burundi: CountryCodes_burundi,
  cambodia: CountryCodes_cambodia,
  cameroon: CountryCodes_cameroon,
  canada: CountryCodes_canada,
  capeVerde: CountryCodes_capeVerde,
  caymanIslands: CountryCodes_caymanIslands,
  centralAfricanRepublic: CountryCodes_centralAfricanRepublic,
  chad: CountryCodes_chad,
  chile: CountryCodes_chile,
  china: CountryCodes_china,
  christmasIsland: CountryCodes_christmasIsland,
  cocosKeelingIslands: CountryCodes_cocosKeelingIslands,
  colombia: CountryCodes_colombia,
  comoros: CountryCodes_comoros,
  congo: CountryCodes_congo,
  democraticRepublicOfTheCongo: CountryCodes_democraticRepublicOfTheCongo,
  cookIslands: CountryCodes_cookIslands,
  costaRica: CountryCodes_costaRica,
  croatia: CountryCodes_croatia,
  cuba: CountryCodes_cuba,
  curacao: CountryCodes_curacao,
  cyprus: CountryCodes_cyprus,
  czechRepublic: CountryCodes_czechRepublic,
  coteDIvoire: CountryCodes_coteDIvoire,
  denmark: CountryCodes_denmark,
  djibouti: CountryCodes_djibouti,
  dominica: CountryCodes_dominica,
  dominicanRepublic: CountryCodes_dominicanRepublic,
  ecuador: CountryCodes_ecuador,
  egypt: CountryCodes_egypt,
  elSalvador: CountryCodes_elSalvador,
  equatorialGuinea: CountryCodes_equatorialGuinea,
  eritrea: CountryCodes_eritrea,
  estonia: CountryCodes_estonia,
  ethiopia: CountryCodes_ethiopia,
  falklandIslandsMalvinas: CountryCodes_falklandIslandsMalvinas,
  faroeIslands: CountryCodes_faroeIslands,
  fiji: CountryCodes_fiji,
  finland: CountryCodes_finland,
  france: CountryCodes_france,
  frenchGuiana: CountryCodes_frenchGuiana,
  frenchPolynesia: CountryCodes_frenchPolynesia,
  frenchSouthernTerritories: CountryCodes_frenchSouthernTerritories,
  gabon: CountryCodes_gabon,
  gambia: CountryCodes_gambia,
  georgia: CountryCodes_georgia,
  germany: CountryCodes_germany,
  ghana: CountryCodes_ghana,
  gibraltar: CountryCodes_gibraltar,
  greece: CountryCodes_greece,
  greenland: CountryCodes_greenland,
  grenada: CountryCodes_grenada,
  guadeloupe: CountryCodes_guadeloupe,
  guam: CountryCodes_guam,
  guatemala: CountryCodes_guatemala,
  guernsey: CountryCodes_guernsey,
  guinea: CountryCodes_guinea,
  guineaBissau: CountryCodes_guineaBissau,
  guyana: CountryCodes_guyana,
  haiti: CountryCodes_haiti,
  heardIslandAndMcDonaldIslands: CountryCodes_heardIslandAndMcDonaldIslands,
  honduras: CountryCodes_honduras,
  hongKong: CountryCodes_hongKong,
  hungary: CountryCodes_hungary,
  iceland: CountryCodes_iceland,
  india: CountryCodes_india,
  indonesia: CountryCodes_indonesia,
  iran: CountryCodes_iran,
  iraq: CountryCodes_iraq,
  ireland: CountryCodes_ireland,
  isleofMan: CountryCodes_isleofMan,
  israel: CountryCodes_israel,
  italy: CountryCodes_italy,
  jamaica: CountryCodes_jamaica,
  japan: CountryCodes_japan,
  jersey: CountryCodes_jersey,
  jordan: CountryCodes_jordan,
  kazakhstan: CountryCodes_kazakhstan,
  kenya: CountryCodes_kenya,
  kiribati: CountryCodes_kiribati,
  northKorea: CountryCodes_northKorea,
  southKorea: CountryCodes_southKorea,
  kuwait: CountryCodes_kuwait,
  kyrgyzstan: CountryCodes_kyrgyzstan,
  lao: CountryCodes_lao,
  latvia: CountryCodes_latvia,
  lebanon: CountryCodes_lebanon,
  lesotho: CountryCodes_lesotho,
  liberia: CountryCodes_liberia,
  libya: CountryCodes_libya,
  liechtenstein: CountryCodes_liechtenstein,
  lithuania: CountryCodes_lithuania,
  luxembourg: CountryCodes_luxembourg,
  macao: CountryCodes_macao,
  macedonia: CountryCodes_macedonia,
  madagascar: CountryCodes_madagascar,
  malawi: CountryCodes_malawi,
  malaysia: CountryCodes_malaysia,
  maldives: CountryCodes_maldives,
  mali: CountryCodes_mali,
  malta: CountryCodes_malta,
  marshallIslands: CountryCodes_marshallIslands,
  martinique: CountryCodes_martinique,
  mauritania: CountryCodes_mauritania,
  mauritius: CountryCodes_mauritius,
  mayotte: CountryCodes_mayotte,
  mexico: CountryCodes_mexico,
  micronesia: CountryCodes_micronesia,
  moldova: CountryCodes_moldova,
  monaco: CountryCodes_monaco,
  mongolia: CountryCodes_mongolia,
  montenegro: CountryCodes_montenegro,
  montserrat: CountryCodes_montserrat,
  morocco: CountryCodes_morocco,
  mozambique: CountryCodes_mozambique,
  myanmar: CountryCodes_myanmar,
  namibia: CountryCodes_namibia,
  nauru: CountryCodes_nauru,
  nepal: CountryCodes_nepal,
  netherlands: CountryCodes_netherlands,
  newCaledonia: CountryCodes_newCaledonia,
  newZealand: CountryCodes_newZealand,
  nicaragua: CountryCodes_nicaragua,
  niger: CountryCodes_niger,
  nigeria: CountryCodes_nigeria,
  niue: CountryCodes_niue,
  norfolkIsland: CountryCodes_norfolkIsland,
  northernMarianaIslands: CountryCodes_northernMarianaIslands,
  norway: CountryCodes_norway,
  oman: CountryCodes_oman,
  pakistan: CountryCodes_pakistan,
  palau: CountryCodes_palau,
  palestine: CountryCodes_palestine,
  panama: CountryCodes_panama,
  papuaNewGuinea: CountryCodes_papuaNewGuinea,
  paraguay: CountryCodes_paraguay,
  peru: CountryCodes_peru,
  philippines: CountryCodes_philippines,
  pitcairn: CountryCodes_pitcairn,
  poland: CountryCodes_poland,
  portugal: CountryCodes_portugal,
  puertoRico: CountryCodes_puertoRico,
  qatar: CountryCodes_qatar,
  romania: CountryCodes_romania,
  russianFederation: CountryCodes_russianFederation,
  rwanda: CountryCodes_rwanda,
  reunion: CountryCodes_reunion,
  saintBarthelemy: CountryCodes_saintBarthelemy,
  saintHelena: CountryCodes_saintHelena,
  saintKittsAndNevis: CountryCodes_saintKittsAndNevis,
  saintLucia: CountryCodes_saintLucia,
  saintMartinFrenchPart: CountryCodes_saintMartinFrenchPart,
  saintPierreAndMiquelon: CountryCodes_saintPierreAndMiquelon,
  saintVincentAndtheGrenadines: CountryCodes_saintVincentAndtheGrenadines,
  samoa: CountryCodes_samoa,
  sanMarino: CountryCodes_sanMarino,
  saoTomeAndPrincipe: CountryCodes_saoTomeAndPrincipe,
  saudiArabia: CountryCodes_saudiArabia,
  senegal: CountryCodes_senegal,
  serbia: CountryCodes_serbia,
  seychelles: CountryCodes_seychelles,
  sierraLeone: CountryCodes_sierraLeone,
  singapore: CountryCodes_singapore,
  sintMaartenDutchPart: CountryCodes_sintMaartenDutchPart,
  slovakia: CountryCodes_slovakia,
  slovenia: CountryCodes_slovenia,
  solomonIslands: CountryCodes_solomonIslands,
  somalia: CountryCodes_somalia,
  southAfrica: CountryCodes_southAfrica,
  southGeorgiaAndtheSouthSandwichIslands: CountryCodes_southGeorgiaAndtheSouthSandwichIslands,
  southSudan: CountryCodes_southSudan,
  spain: CountryCodes_spain,
  sriLanka: CountryCodes_sriLanka,
  sudan: CountryCodes_sudan,
  suriname: CountryCodes_suriname,
  svalbardAndJanMayen: CountryCodes_svalbardAndJanMayen,
  swaziland: CountryCodes_swaziland,
  sweden: CountryCodes_sweden,
  switzerland: CountryCodes_switzerland,
  syrianArabRepublic: CountryCodes_syrianArabRepublic,
  taiwan: CountryCodes_taiwan,
  tajikistan: CountryCodes_tajikistan,
  unitedRepublicOfTanzania: CountryCodes_unitedRepublicOfTanzania,
  thailand: CountryCodes_thailand,
  timorLeste: CountryCodes_timorLeste,
  togo: CountryCodes_togo,
  tokelau: CountryCodes_tokelau,
  tonga: CountryCodes_tonga,
  trinidadAndTobago: CountryCodes_trinidadAndTobago,
  tunisia: CountryCodes_tunisia,
  turkey: CountryCodes_turkey,
  turkmenistan: CountryCodes_turkmenistan,
  turksandCaicosIslands: CountryCodes_turksandCaicosIslands,
  tuvalu: CountryCodes_tuvalu,
  uganda: CountryCodes_uganda,
  ukraine: CountryCodes_ukraine,
  unitedArabEmirates: CountryCodes_unitedArabEmirates,
  unitedKingdom: CountryCodes_unitedKingdom,
  unitedStates: CountryCodes_unitedStates,
  unitedStatesMinorOutlyingIslands: CountryCodes_unitedStatesMinorOutlyingIslands,
  uruguay: CountryCodes_uruguay,
  uzbekistan: CountryCodes_uzbekistan,
  vanuatu: CountryCodes_vanuatu,
  vaticanCityState: CountryCodes_vaticanCityState,
  venezuela: CountryCodes_venezuela,
  vietNam: CountryCodes_vietNam,
  britishVirginIslands: CountryCodes_britishVirginIslands,
  usVirginIslands: CountryCodes_usVirginIslands,
  wallisAndFutuna: CountryCodes_wallisAndFutuna,
  westernSahara: CountryCodes_westernSahara,
  yemen: CountryCodes_yemen,
  zambia: CountryCodes_zambia,
  zimbabwe: CountryCodes_zimbabwe
};

exports.CountryCodes = CountryCodes;
/* No side effect */
