// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function validateCountryCode(countryCode) {
  if (countryCode !== undefined) {
    return countryCode;
  }
  
}

function makePhoneNumber(countryCode, areaCode, prefix, lineNumber, extension) {
  if (countryCode !== undefined) {
    return {
            countryCode: countryCode,
            areaCode: areaCode,
            prefix: prefix,
            lineNumber: lineNumber,
            extension: extension
          };
  }
  throw {
        RE_EXN_ID: "Invalid_argument",
        _1: "Invalid Country Code",
        Error: new Error()
      };
}

var PhoneNumber = {
  CC: undefined,
  validateCountryCode: validateCountryCode,
  makePhoneNumber: makePhoneNumber
};

exports.PhoneNumber = PhoneNumber;
/* No side effect */
