// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var VirtualNode;

var Component;

var Props;

exports.VirtualNode = VirtualNode;
exports.Component = Component;
exports.Props = Props;
/* No side effect */
